############################################################
#
# 用户微服务
# web访问端口号  约定：7001
#
############################################################
server:
  port: ${port:7001}
spring:
  application:
    name: springcloud-eureka-cluster-${server.port}
############################################################
#
# eureka 配置信息
#
############################################################
eureka:
  instance:
    # 集群中每个eureka的名字都是唯一的
    hostname: eureka-cluster-${server.port}
  # 自定义集群端口
  cluster-node-port-2: ${p2:7002}
  cluster-node-port-3: ${p3:7003}
  client:
    # 是否腰包当前eureka server注册到自己
    register-with-eureka: false
    # 从注册中心获得检索服务实例，server没有必要 直接false即可
    fetch-registry: false
    # 单实例配置自己的服务地址，高可用则配置多个地址
    service-url:
      defaultZone: http://eureka-cluster-${eureka.cluster-node-port-2}:${eureka.cluster-node-port-2}/eureka/,http://eureka-cluster-${eureka.cluster-node-port-3}:${eureka.cluster-node-port-3}/eureka/
  server:
    # 关闭eureka的自我保护功能
    enable-self-preservation: true
    # 清理无效节点的时间，可以缩短为5s，默认60s
    eviction-interval-timer-in-ms: 5000