############################################################
#
# 用户微服务
# web访问端口号  约定：7001
#
############################################################
spring:
  application:
    name: springcloud-eureka-cluster-${server.port}
  profiles:
    active: dev