spring:
  application:
    name: user-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 蛇形名称格式  banner_id
    #    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  ############################################################
  #
  # 邮箱配置
  #
  ############################################################
  mail:
    #邮件发送者
    mailSender: 5219824@qq.com
    # smtp.163.com
    host: smtp.qq.com
    username: 5219824@qq.com
    #QQ邮箱的授权码 163是邮箱密码
    password: gprsxzwvhaucbhbf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    check-template-location: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=utf-8
    # 关闭缓存, 即时刷新, 上线生产环境需要改为true
    cache: false
  freemarker:
    check-template-location: false
    charset: UTF-8
    content-type: text/html;charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
    allow-session-override: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.fans.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wechat:
  appid: wxb596d23b0c9f5dd2
  appsecret: ac919349bf19abdcd5c834c42a631a4a
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code
############################################################
#
# eureka client 配置信息
#
############################################################
eureka:
  # 自定义eureka server的信息
  server:
    hostname: eureka
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      #defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/
  instance:
    # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-renewal-interval-in-seconds: 3
    # eureka 举例最近的一次心跳等待提出的时间，默认90s
    lease-expiration-duration-in-seconds: 5
# 配置hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 设置hystrix超时时间，超过2秒触发降级
            timeoutInMilliseconds: 2000
            # 配置断路器
      circuitBreaker:
        enabled: true
        # 触发熔断最小请求次数，默认：20
        requestVolumeThreshold: 10
        # 熔断后过几秒后尝试半开状态（请求重试），默认：5s
        sleepWindowInMilliseconds: 15000
        # 触发熔断的失败率（异常率/阈值），默认：50
        errorThresholdPercentage: 50