interceptor:
  beans:
    #\u6743\u9650\u9A8C\u8BC1\u62E6\u622A\u5668 \u68C0\u6D4B\u662F\u5426\u6709scope\u6CE8\u89E3\u624D\u4F1A\u751F\u6548
    permissionInterceptor:
      add-path-patterns:
        - /banner/test
      exclude-path-patterns:
