############################################################
#
# web访问端口号  约定：7001
#
############################################################
server:
  port: ${port:7001}
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
#
# 日志 logback 配置
#
############################################################
logging:
  config: classpath:logback.xml
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    url: jdbc:mysql://localhost:3306/kapok?characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true&autoReconnect=true&useUnicode=true
    username: root
    password: root
    desc: 系统默认数据源
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: PT1H
  redis:
    # redis数据库索引(默认为0)
    database: 0
    # redis服务器IP地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # redis密码，默认为空
    password: sl6819961
    # 连接redis超时时间（毫秒）
    timeout: PT2S
    #jedis连接池
    ###############################
    jedis:
      pool:
        # 最大等待时间
        max-wait: 1000
        # 最小空闲数量
        min-idle: 1
        # 最大空闲数量
        max-idle: 10
        # 最大连接数量
        max-active: 1000
      # 集群节点配置
    sharded-cluster:
      nodes:
        - 127.0.0.1:6379
  # mongodb配置
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017
      database: test
  #  # rabbitMq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
swagger:
  enable: true
##多数据源的配置
dynamic:
  datasource:
    cloudy:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloudy?characterEncoding=utf-8&serverTimezone=GMT%2b8&allowMultiQueries=true
      username: root
      password: root
      desc: Security框架
    security:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&serverTimezone=GMT%2b8&allowMultiQueries=true
      username: root
      password: root
      desc: Rbac框架