############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: eureka
  profiles:
    active: dev